site_name: Testing Read the docs
site_description: Testing Read the docs
site_url: http://localhost:8000
theme:
  name: material
  # custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: nayan32biswas/test-read-the-docs-with-mkdocs
repo_url: https://github.com/nayan32biswas/test-read-the-docs-with-mkdocs
edit_uri: ""
nav:
  - index.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nayan32biswas

extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js
